import { JobPosition, SystemSettings } from '../types.js';
import { GOVT_JOBS } from './govtJobs.js';

export const DEFAULT_INTERVIEW_POLICY = `1. Original Documents Mandatory: Candidates must bring their Original CNIC, Educational Certificates, and Printed Application Pass Slip on the interview day.
2. Schedule Notification: Official interview dates, venue details, and reporting times will be communicated via SMS and Email after application fee & document verification.
3. Reporting Time: Candidates must report at the test/interview venue at least 30 minutes before the scheduled time. Late arrivals (beyond 15 minutes) will not be permitted entry.
4. Electronic Devices Prohibited: Mobile phones, smartwatches, calculators, and electronic storage devices are strictly banned inside the examination/interview premises.
5. TA / DA Notice: No Traveling Allowance or Daily Allowance (TA/DA) will be paid to candidates for attending the test or interview.
6. Verification & Disqualification: Any misrepresentation, forged documents, or impersonation will lead to instant disqualification and legal prosecution under applicable laws.`;

export const DEFAULT_SETTINGS: SystemSettings = {
  applicationFee: 300,
  jazzcash: {
    accountTitle: 'JobsHub Official Portal',
    accountNumber: '0301-8899771',
    instructions: 'Open JazzCash App or dial *786#. Select Send Money -> To JazzCash Account. Enter Account Number 0301-8899771. Enter Amount 300 PKR. Confirm payment and take a screenshot.'
  },
  easypaisa: {
    accountTitle: 'JobsHub Official Portal',
    accountNumber: '0345-8899772',
    instructions: 'Open Easypaisa App or dial *786#. Select Send Money -> EasyPaisa Transfer. Enter Account Number 0345-8899772. Enter Amount 300 PKR. Complete payment and take a screenshot.'
  },
  interviewPolicy: DEFAULT_INTERVIEW_POLICY
};

export const DEFAULT_JOBS: JobPosition[] = [
  // --- CATEGORY 1: Primary / Middle (10 Jobs) ---
  {
    id: 'job-1',
    title: 'Data Entry Operator',
    department: 'Data Management & Operations',
    category: 'Data Entry & Typing',
    minQualification: 'Primary',
    qualificationRequired: 'Primary / Middle or Higher',
    jobType: 'Freelance / Remote',
    ageLimit: '18 - 45 Years',
    vacancies: 50,
    location: 'Remote / Work From Home',
    salaryRange: 'PKR 30,000 - 40,000 / month',
    deadline: '2026-09-30',
    description: 'Basic keyboard entry of offline forms into Excel and Google Sheets. Training provided.',
    requiredSkills: ['Basic Typing', 'Excel', 'Data Checking'],
    status: 'active',
    campaigns: ['freelancers', 'factory-workers', 'government']
  },
  {
    id: 'job-2',
    title: 'Online Form Filling Assistant',
    department: 'Digital Administration',
    category: 'Virtual Assistance & Admin Support',
    minQualification: 'Primary',
    qualificationRequired: 'Primary / Middle or Higher',
    jobType: 'Part-Time / Online',
    ageLimit: '18 - 45 Years',
    vacancies: 40,
    location: 'Remote / Anywhere in Pakistan',
    salaryRange: 'PKR 25,000 - 35,000 / month',
    deadline: '2026-09-30',
    description: 'Assist in submitting online customer registrations and verifying form field values accurately.',
    requiredSkills: ['Internet Browsing', 'Form Filling', 'Attention to Detail'],
    status: 'active',
    campaigns: ['freelancers']
  },
  {
    id: 'job-3',
    title: 'Product Listing Assistant',
    department: 'E-commerce Operations',
    category: 'Retail & Store',
    minQualification: 'Primary',
    qualificationRequired: 'Primary / Middle or Higher',
    jobType: 'Freelance / Task Based',
    ageLimit: '18 - 40 Years',
    vacancies: 35,
    location: 'Remote / Online',
    salaryRange: 'PKR 28,000 - 38,000 / month',
    deadline: '2026-09-25',
    description: 'Copying product titles, images, and prices into inventory software and marketplace stores.',
    requiredSkills: ['Copy Paste', 'Product Cataloging', 'Basic English'],
    status: 'active',
    campaigns: ['freelancers', 'factory-workers', 'private']
  },
  {
    id: 'job-4',
    title: 'Simple Typing Work',
    department: 'Document Services',
    category: 'Data Entry & Typing',
    minQualification: 'Primary',
    qualificationRequired: 'Primary / Middle or Higher',
    jobType: 'Freelance / Remote',
    ageLimit: '18 - 50 Years',
    vacancies: 60,
    location: 'Remote / Work From Home',
    salaryRange: 'PKR 25,000 - 35,000 / month',
    deadline: '2026-10-15',
    description: 'Typing scanned Urdu and English text documents into Word format with standard speed.',
    requiredSkills: ['Typing', 'MS Word', 'Document Formatting'],
    status: 'active',
    campaigns: ['freelancers', 'factory-workers']
  },
  {
    id: 'job-5',
    title: 'Online Chat Support Assistant',
    department: 'Customer Relations',
    category: 'Customer Support & Chat',
    minQualification: 'Primary',
    qualificationRequired: 'Primary / Middle or Higher',
    jobType: 'Remote Shift Work',
    ageLimit: '18 - 35 Years',
    vacancies: 30,
    location: 'Remote / Online',
    salaryRange: 'PKR 32,000 - 42,000 / month',
    deadline: '2026-09-28',
    description: 'Answering basic customer chat inquiries using canned responses and forwarding tickets.',
    requiredSkills: ['Live Chat', 'Customer Care', 'Communication'],
    status: 'active',
    campaigns: ['freelancers', 'private']
  },
  {
    id: 'job-6',
    title: 'Social Media Posting Assistant',
    department: 'Marketing & Outreach',
    category: 'Digital Marketing & Social Media',
    minQualification: 'Primary',
    qualificationRequired: 'Primary / Middle or Higher',
    jobType: 'Part-Time / Remote',
    ageLimit: '18 - 35 Years',
    vacancies: 45,
    location: 'Remote / Online',
    salaryRange: 'PKR 25,000 - 35,000 / month',
    deadline: '2026-10-05',
    description: 'Publishing pre-approved promotional posts and images across client WhatsApp and Facebook groups.',
    requiredSkills: ['Facebook', 'WhatsApp', 'Social Media'],
    status: 'active',
    campaigns: ['freelancers', 'suthra-punjab', 'private']
  },
  {
    id: 'job-7',
    title: 'Virtual Assistant — Basic Tasks',
    department: 'Admin Support Services',
    category: 'Virtual Assistance & Admin Support',
    minQualification: 'Primary',
    qualificationRequired: 'Primary / Middle or Higher',
    jobType: 'Freelance / Hourly',
    ageLimit: '18 - 40 Years',
    vacancies: 25,
    location: 'Remote / Online',
    salaryRange: 'PKR 30,000 - 40,000 / month',
    deadline: '2026-09-30',
    description: 'Handling routine administrative tasks like schedule reminders, link organization, and file downloads.',
    requiredSkills: ['Task Management', 'Google Drive', 'Organization'],
    status: 'active',
    campaigns: ['freelancers', 'government']
  },
  {
    id: 'job-8',
    title: 'Image Upload Assistant',
    department: 'Digital Media Operations',
    category: 'Graphic Design & Multimedia',
    minQualification: 'Primary',
    qualificationRequired: 'Primary / Middle or Higher',
    jobType: 'Freelance / Task Based',
    ageLimit: '18 - 45 Years',
    vacancies: 30,
    location: 'Remote / Online',
    salaryRange: 'PKR 22,000 - 32,000 / month',
    deadline: '2026-09-20',
    description: 'Uploading and tagging photo galleries for events, web products, and digital archives.',
    requiredSkills: ['File Handling', 'Image Tagging', 'Basic Web Navigation'],
    status: 'active',
    campaigns: ['freelancers', 'factory-workers']
  },
  {
    id: 'job-9',
    title: 'Content Upload Assistant',
    department: 'Web Publishing',
    category: 'Content Writing & SEO',
    minQualification: 'Primary',
    qualificationRequired: 'Primary / Middle or Higher',
    jobType: 'Part-Time / Online',
    ageLimit: '18 - 40 Years',
    vacancies: 20,
    location: 'Remote / Work From Home',
    salaryRange: 'PKR 28,000 - 38,000 / month',
    deadline: '2026-10-10',
    description: 'Uploading written articles and PDFs into portal CMS and assigning appropriate categories.',
    requiredSkills: ['Data Entry', 'CMS Upload', 'File Formatting'],
    status: 'active',
    campaigns: ['freelancers', 'government']
  },
  {
    id: 'job-10',
    title: 'Online Survey / Research Assistant',
    department: 'Market Intelligence',
    category: 'Field Staff',
    minQualification: 'Primary',
    qualificationRequired: 'Primary / Middle or Higher',
    jobType: 'Freelance / Remote',
    ageLimit: '18 - 45 Years',
    vacancies: 50,
    location: 'Remote / Anywhere in Pakistan',
    salaryRange: 'PKR 25,000 - 35,000 / month',
    deadline: '2026-10-01',
    description: 'Gathering public survey feedback, recording consumer responses, and compiling daily tally reports.',
    requiredSkills: ['Surveying', 'Data Collection', 'Feedback Recording'],
    status: 'active',
    campaigns: ['freelancers', 'suthra-punjab', 'government']
  },

  // --- CATEGORY 2: Matric (5 Jobs) ---
  {
    id: 'job-11',
    title: 'Video Editing Assistant',
    department: 'Multimedia & Creative Studio',
    category: 'Graphic Design & Multimedia',
    minQualification: 'Matric',
    qualificationRequired: 'Matric or Higher',
    jobType: 'Freelance / Project Based',
    ageLimit: '18 - 35 Years',
    vacancies: 25,
    location: 'Remote / Work From Home',
    salaryRange: 'PKR 40,000 - 55,000 / month',
    deadline: '2026-09-28',
    description: 'Trimming short video clips, inserting titles, adding background audio and subtitles for YouTube shorts & Reels.',
    requiredSkills: ['CapCut', 'Premiere Pro', 'Video Trimming', 'Subtitles'],
    status: 'active',
    campaigns: ['freelancers', 'private']
  },
  {
    id: 'job-12',
    title: 'Graphic Design Assistant',
    department: 'Creative & Brand Team',
    category: 'Graphic Design & Multimedia',
    minQualification: 'Matric',
    qualificationRequired: 'Matric or Higher',
    jobType: 'Freelance / Remote',
    ageLimit: '18 - 35 Years',
    vacancies: 30,
    location: 'Remote / Online',
    salaryRange: 'PKR 38,000 - 52,000 / month',
    deadline: '2026-09-26',
    description: 'Designing promotional flyers, Canva banners, social media thumbnails, and basic photo editing.',
    requiredSkills: ['Canva', 'Photoshop', 'Banner Design', 'Color Aesthetics'],
    status: 'active',
    campaigns: ['freelancers', 'private']
  },
  {
    id: 'job-13',
    title: 'Customer Support Representative',
    department: 'Helpdesk & Client Care',
    category: 'Customer Service',
    minQualification: 'Matric',
    qualificationRequired: 'Matric or Higher',
    jobType: 'Full-Time / Remote',
    ageLimit: '18 - 32 Years',
    vacancies: 40,
    location: 'Remote / Online',
    salaryRange: 'PKR 42,000 - 58,000 / month',
    deadline: '2026-10-05',
    description: 'Handling incoming telephonic and chat queries regarding test scheduling, application fees, and results.',
    requiredSkills: ['Call Handling', 'Urdu / English Fluency', 'CRM Software'],
    status: 'active',
    campaigns: ['suthra-punjab', 'government', 'private']
  },
  {
    id: 'job-14',
    title: 'E-commerce Store Assistant',
    department: 'Online Commerce Unit',
    category: 'Retail & Store',
    minQualification: 'Matric',
    qualificationRequired: 'Matric or Higher',
    jobType: 'Remote Shift Work',
    ageLimit: '18 - 35 Years',
    vacancies: 20,
    location: 'Remote / Work From Home',
    salaryRange: 'PKR 35,000 - 50,000 / month',
    deadline: '2026-10-12',
    description: 'Managing online store orders, dispatch tracking, customer return requests, and stock log updates.',
    requiredSkills: ['Shopify / WooCommerce', 'Order Dispatch', 'Inventory'],
    status: 'active',
    campaigns: ['factory-workers', 'private']
  },
  {
    id: 'job-15',
    title: 'Voice Over / Audio Recording Assistant',
    department: 'Media Production',
    category: 'Graphic Design & Multimedia',
    minQualification: 'Matric',
    qualificationRequired: 'Matric or Higher',
    jobType: 'Freelance / Per Project',
    ageLimit: '18 - 40 Years',
    vacancies: 15,
    location: 'Remote / Home Studio',
    salaryRange: 'PKR 35,000 - 50,000 / month',
    deadline: '2026-09-30',
    description: 'Recording clear audio voiceovers for educational videos, commercial announcements, and IVR lines.',
    requiredSkills: ['Voice Modulation', 'Urdu Diction', 'Audio Editing'],
    status: 'active',
    campaigns: ['freelancers', 'private']
  },

  // --- CATEGORY 3: Intermediate and Above (10 Jobs) ---
  {
    id: 'job-16',
    title: 'Content Writer',
    department: 'Editorial & Publications',
    category: 'Content Writing & SEO',
    minQualification: 'Intermediate',
    qualificationRequired: 'Intermediate or Higher',
    jobType: 'Freelance / Remote',
    ageLimit: '18 - 38 Years',
    vacancies: 30,
    location: 'Remote / Online',
    salaryRange: 'PKR 50,000 - 70,000 / month',
    deadline: '2026-10-15',
    description: 'Writing engaging blog posts, portal notices, job guides, and educational articles with high quality.',
    requiredSkills: ['Article Writing', 'SEO Content', 'Grammar', 'Research'],
    status: 'active',
    campaigns: ['freelancers', 'government', 'private']
  },
  {
    id: 'job-17',
    title: 'Copywriter',
    department: 'Marketing & Brand Communications',
    category: 'Content Writing & SEO',
    minQualification: 'Intermediate',
    qualificationRequired: 'Intermediate or Higher',
    jobType: 'Freelance / Contract',
    ageLimit: '18 - 38 Years',
    vacancies: 15,
    location: 'Remote / Work From Home',
    salaryRange: 'PKR 55,000 - 75,000 / month',
    deadline: '2026-10-10',
    description: 'Crafting persuasive ad copies, landing page text, email newsletters, and promotional slogans.',
    requiredSkills: ['Persuasive Writing', 'Ad Copies', 'Email Campaigns'],
    status: 'active',
    campaigns: ['freelancers', 'private']
  },
  {
    id: 'job-18',
    title: 'Social Media Manager',
    department: 'Digital Marketing Division',
    category: 'Digital Marketing & Social Media',
    minQualification: 'Intermediate',
    qualificationRequired: 'Intermediate or Higher',
    jobType: 'Full-Time / Remote',
    ageLimit: '20 - 38 Years',
    vacancies: 12,
    location: 'Remote / Online',
    salaryRange: 'PKR 60,000 - 85,000 / month',
    deadline: '2026-10-20',
    description: 'Overseeing social channels strategy, content calendars, community growth, and campaign analytics.',
    requiredSkills: ['Social Strategy', 'Meta Business Suite', 'Analytics'],
    status: 'active',
    campaigns: ['private', 'government']
  },
  {
    id: 'job-19',
    title: 'Digital Marketing Specialist',
    department: 'Growth Marketing',
    category: 'Sales & Marketing',
    minQualification: 'Intermediate',
    qualificationRequired: 'Intermediate or Higher',
    jobType: 'Full-Time / Remote',
    ageLimit: '20 - 40 Years',
    vacancies: 10,
    location: 'Remote / Online',
    salaryRange: 'PKR 65,000 - 90,000 / month',
    deadline: '2026-10-25',
    description: 'Running paid ad campaigns on Google Ads, Meta Ads, TikTok Ads, and tracking conversion ROI.',
    requiredSkills: ['Google Ads', 'Facebook Ads', 'PPC', 'Funnel Optimization'],
    status: 'active',
    campaigns: ['private', 'government']
  },
  {
    id: 'job-20',
    title: 'SEO Specialist',
    department: 'Search Engine Optimization',
    category: 'Content Writing & SEO',
    minQualification: 'Intermediate',
    qualificationRequired: 'Intermediate or Higher',
    jobType: 'Remote / Hybrid',
    ageLimit: '20 - 40 Years',
    vacancies: 10,
    location: 'Remote / Online',
    salaryRange: 'PKR 60,000 - 85,000 / month',
    deadline: '2026-10-18',
    description: 'On-page SEO, technical audits, backlink building, keyword research, and Search Console management.',
    requiredSkills: ['Keyword Research', 'Technical SEO', 'Ahrefs', 'Search Console'],
    status: 'active',
    campaigns: ['private', 'government']
  },
  {
    id: 'job-21',
    title: 'WordPress Developer',
    department: 'Web Engineering',
    category: 'Web & Software Development',
    minQualification: 'Intermediate',
    qualificationRequired: 'Intermediate or Higher',
    jobType: 'Freelance / Remote',
    ageLimit: '18 - 40 Years',
    vacancies: 15,
    location: 'Remote / Work From Home',
    salaryRange: 'PKR 65,000 - 95,000 / month',
    deadline: '2026-10-30',
    description: 'Customizing WordPress themes, Elementor layouts, WooCommerce setups, and plugin customization.',
    requiredSkills: ['WordPress', 'PHP', 'Elementor', 'WooCommerce', 'CSS'],
    status: 'active',
    campaigns: ['freelancers', 'private']
  },
  {
    id: 'job-22',
    title: 'Web Developer',
    department: 'Software & Web Systems',
    category: 'Web & Software Development',
    minQualification: 'Intermediate',
    qualificationRequired: 'Intermediate or Higher',
    jobType: 'Full-Time / Remote',
    ageLimit: '20 - 40 Years',
    vacancies: 20,
    location: 'Remote / Online',
    salaryRange: 'PKR 80,000 - 120,000 / month',
    deadline: '2026-11-05',
    description: 'Building responsive web interfaces and full-stack applications using React, Node.js, and TypeScript.',
    requiredSkills: ['React', 'Node.js', 'TypeScript', 'Tailwind CSS', 'REST API'],
    status: 'active',
    campaigns: ['government', 'private']
  },
  {
    id: 'job-23',
    title: 'Mobile App Developer',
    department: 'App Development Division',
    category: 'Web & Software Development',
    minQualification: 'Intermediate',
    qualificationRequired: 'Intermediate or Higher',
    jobType: 'Full-Time / Remote',
    ageLimit: '20 - 40 Years',
    vacancies: 10,
    location: 'Remote / Online',
    salaryRange: 'PKR 85,000 - 130,000 / month',
    deadline: '2026-11-10',
    description: 'Developing cross-platform mobile apps for Android & iOS using Flutter or React Native.',
    requiredSkills: ['Flutter / React Native', 'Dart', 'Mobile UI', 'API Integration'],
    status: 'active',
    campaigns: ['government', 'private']
  },
  {
    id: 'job-24',
    title: 'UI/UX Designer',
    department: 'Product Design Studio',
    category: 'Graphic Design & Multimedia',
    minQualification: 'Intermediate',
    qualificationRequired: 'Intermediate or Higher',
    jobType: 'Freelance / Contract',
    ageLimit: '20 - 38 Years',
    vacancies: 8,
    location: 'Remote / Online',
    salaryRange: 'PKR 70,000 - 110,000 / month',
    deadline: '2026-10-28',
    description: 'Designing wireframes, interactive Figma prototypes, design systems, and mobile/web app user journeys.',
    requiredSkills: ['Figma', 'Prototyping', 'User Research', 'Design Systems'],
    status: 'active',
    campaigns: ['freelancers', 'private']
  },
  {
    id: 'job-25',
    title: 'Software Developer',
    department: 'Core Engineering Dept',
    category: 'Web & Software Development',
    minQualification: 'Intermediate',
    qualificationRequired: 'Intermediate or Higher',
    jobType: 'Full-Time / Remote',
    ageLimit: '20 - 42 Years',
    vacancies: 15,
    location: 'Remote / Online',
    salaryRange: 'PKR 90,000 - 150,000 / month',
    deadline: '2026-11-15',
    description: 'Designing scalable backend APIs, database architecture, automated tests, and cloud deployments.',
    requiredSkills: ['JavaScript / Python', 'SQL / NoSQL', 'System Architecture', 'Git'],
    status: 'active',
    campaigns: ['government', 'private']
  },

  // --- SPECIALIZED NEW JOBS (Healthcare, Technical, Armed Forces, Pharmacy, Private Hospitals) ---
  {
    id: 'job-26',
    title: 'Medical Officer (Medical Specialist)',
    department: 'District Headquarter Hospital (DHQ)',
    category: 'Government Hospitals & Healthcare',
    minQualification: 'Bachelor',
    qualificationRequired: 'MBBS or Equivalent Medical Degree',
    medicalQualification: 'MBBS + PMDC / PMC Registration Mandatory',
    experienceRequired: '1 Year House Job Completion',
    jobType: 'Full-Time / Govt Regular Post',
    ageLimit: '22 - 38 Years',
    vacancies: 25,
    location: 'DHQ / THQ Hospitals Punjab',
    salaryRange: 'BPS-17 (PKR 110,000 - 160,000 / month)',
    deadline: '2026-10-30',
    description: 'General OPD management, emergency care duty, outdoor patient examination, and clinical record keeping.',
    requiredSkills: ['OPD Diagnosis', 'Emergency Care', 'Patient Management', 'PMDC Certified'],
    status: 'active',
    campaigns: ['government']
  },
  {
    id: 'job-27',
    title: 'Charge Nurse / Staff Nurse',
    department: 'Primary & Secondary Healthcare Dept',
    category: 'Government Hospitals & Healthcare',
    minQualification: 'Diploma',
    qualificationRequired: 'B.Sc Nursing / General Nursing 3-Year Diploma',
    medicalQualification: 'Valid Nursing Council Registration (PNC)',
    experienceRequired: 'Fresh / 1 Year Clinical Internship',
    jobType: 'Full-Time / Shift Work',
    ageLimit: '18 - 35 Years',
    vacancies: 60,
    location: 'Government General Hospitals',
    salaryRange: 'BPS-16 (PKR 75,000 - 105,000 / month)',
    deadline: '2026-11-05',
    description: 'Inpatient ward nursing, medication administration, vital signs tracking, and assist medical officers.',
    requiredSkills: ['Patient Nursing', 'IV Care', 'Ward Management', 'PNC Registered'],
    status: 'active',
    campaigns: ['government']
  },
  {
    id: 'job-28',
    title: 'Govt Hospital Pharmacist',
    department: 'Department of Health & Drug Control',
    category: 'Government Hospitals & Healthcare',
    minQualification: 'Bachelor',
    qualificationRequired: 'Pharm-D (Doctor of Pharmacy)',
    medicalQualification: 'Category A Pharmacy Council Registration',
    experienceRequired: 'Fresh Graduates Eligible',
    jobType: 'Full-Time Regular',
    ageLimit: '21 - 35 Years',
    vacancies: 18,
    location: 'Government Hospital Pharmacy Division',
    salaryRange: 'BPS-17 (PKR 95,000 - 135,000 / month)',
    deadline: '2026-10-25',
    description: 'Supervising hospital drug store distribution, checking prescription safety, and managing inventory logs.',
    requiredSkills: ['Pharmacology', 'Drug Store Management', 'Pharmacy Council Reg'],
    status: 'active',
    campaigns: ['government']
  },
  {
    id: 'job-29',
    title: 'Govt Lab Technician / Pathology Tech',
    department: 'Diagnostic Laboratory Services',
    category: 'Government Hospitals & Healthcare',
    minQualification: 'Diploma',
    qualificationRequired: 'FSc Pre-Medical + Diploma in Medical Lab Technology (MLT)',
    experienceRequired: '1 Year Clinical Laboratory Experience',
    jobType: 'Full-Time Govt Post',
    ageLimit: '18 - 32 Years',
    vacancies: 30,
    location: 'District Diagnostic Labs',
    salaryRange: 'BPS-12 (PKR 55,000 - 75,000 / month)',
    deadline: '2026-10-20',
    description: 'Collecting blood & tissue samples, operating hematology analyzers, and logging test result sheets.',
    requiredSkills: ['Blood Sample Draw', 'Lab Analyzers', 'Pathology Testing'],
    status: 'active',
    campaigns: ['government']
  },
  {
    id: 'job-30',
    title: 'Electrician & Generator Operator',
    department: 'Public Works Department (PWD)',
    category: 'Government Technical & Skilled Jobs',
    minQualification: 'Diploma',
    qualificationRequired: 'Matric + DAE Electrical / Trade Certificate',
    experienceRequired: '2 Years Electrical & Generator Maintenance',
    jobType: 'Full-Time / Contract',
    ageLimit: '18 - 40 Years',
    vacancies: 40,
    location: 'Govt Complex & Civil Lines',
    salaryRange: 'BPS-11 (PKR 48,000 - 68,000 / month)',
    deadline: '2026-10-18',
    description: 'Installation, wiring repairs, backup generator fault diagnostics, and electrical panel maintenance.',
    requiredSkills: ['Electrical Wiring', 'Generator Repairs', 'Panel Troubleshooting'],
    status: 'active',
    campaigns: ['government']
  },
  {
    id: 'job-31',
    title: 'General Duty Constable',
    department: 'Punjab Police Department',
    category: 'Police',
    minQualification: 'Matric',
    qualificationRequired: 'Matriculation (5 feet 7 inches Minimum Height)',
    experienceRequired: 'Physical Fitness Test Required',
    jobType: 'Uniformed Public Service',
    ageLimit: '18 - 25 Years',
    vacancies: 150,
    location: 'District Police Lines',
    salaryRange: 'BPS-07 (PKR 50,000 - 68,000 / month)',
    deadline: '2026-11-15',
    description: 'Patrol duty, law & order enforcement, public protection, escort duty, and police station support.',
    requiredSkills: ['Physical Fitness', 'Law Enforcement', 'Public Security'],
    status: 'active',
    campaigns: ['government']
  },
  {
    id: 'job-32',
    title: 'Aero-Trade Soldier Candidate',
    department: 'Pakistan Air Force Recruitment',
    category: 'Pakistan Air Force',
    minQualification: 'Matric',
    qualificationRequired: 'Matric Science with 60% Marks',
    experienceRequired: 'Unmarried Male Citizens of Pakistan',
    jobType: 'Regular Defense Forces',
    ageLimit: '16.5 - 21 Years',
    vacancies: 80,
    location: 'PAF Airbases Nationwide',
    salaryRange: 'Govt Defense Pay Structure + Allowances',
    deadline: '2026-11-01',
    description: 'Technical aircraft assistance, radar monitoring support, airbase security, and technical trade duties.',
    requiredSkills: ['Science Basics', 'Physical Agility', 'Discipline'],
    status: 'active',
    campaigns: ['government']
  },
  {
    id: 'job-33',
    title: 'Senior Pharmacist & Store Incharge',
    department: 'Al-Shifa Pharmacy Chain',
    category: 'Medical Stores & Pharmacy',
    minQualification: 'Bachelor',
    qualificationRequired: 'Pharm-D / Doctor of Pharmacy',
    medicalQualification: 'Category A Pharmacy Council License',
    experienceRequired: '1 - 3 Years Pharmacy Management',
    jobType: 'Full-Time Shift',
    ageLimit: '22 - 40 Years',
    vacancies: 15,
    location: 'Lahore, Karachi, Islamabad',
    salaryRange: 'PKR 75,000 - 110,000 / month',
    deadline: '2026-10-30',
    description: 'Managing counter sales, prescription dispensing, medicine inventory ordering, and staff supervision.',
    requiredSkills: ['Medicine Dispensing', 'POS Software', 'Inventory Control'],
    status: 'active',
    campaigns: ['private']
  },
  {
    id: 'job-34',
    title: 'Pharmacy Assistant & Dispenser',
    department: 'MedPlus Pharmacy',
    category: 'Medical Stores & Pharmacy',
    minQualification: 'Intermediate',
    qualificationRequired: 'Matric / FSc + Dispenser Diploma',
    experienceRequired: '6 Months Pharmacy Sales Experience',
    jobType: 'Full-Time / Night Shift Available',
    ageLimit: '18 - 35 Years',
    vacancies: 35,
    location: 'All Major Cities',
    salaryRange: 'PKR 35,000 - 52,000 / month',
    deadline: '2026-10-15',
    description: 'Assisting customers at counter, checking medicine stock labels, updating computerized billing, and stocking shelves.',
    requiredSkills: ['Prescription Reading', 'Counter Sales', 'Computer Billing'],
    status: 'active',
    campaigns: ['private']
  },
  {
    id: 'job-35',
    title: 'Medicine Delivery Rider',
    department: 'Express Pharmacy Home Delivery',
    category: 'Medical Stores & Pharmacy',
    minQualification: 'Matric',
    qualificationRequired: 'Matric / Middle + Valid Motorcycle License',
    experienceRequired: 'Rider / Delivery Experience Preferred',
    jobType: 'Full-Time / Part-Time Shifts',
    ageLimit: '18 - 38 Years',
    vacancies: 50,
    location: 'Lahore, Rawalpindi, Faisalabad',
    salaryRange: 'PKR 32,000 - 45,000 + Fuel Allowance',
    deadline: '2026-10-10',
    description: 'Delivering urgent doorstep pharmacy orders to patients, collecting payments, and maintaining delivery logs.',
    requiredSkills: ['Bike Riding', 'City Navigation', 'Customer Care'],
    status: 'active',
    campaigns: ['private']
  },
  {
    id: 'job-36',
    title: 'HVAC & AC Maintenance Technician',
    department: 'Pak Cool Tech Solutions',
    category: 'Technical & Skilled Jobs',
    minQualification: 'Diploma',
    qualificationRequired: 'DAE HVAC / Refrigeration Certificate',
    experienceRequired: '2 Years AC Repair & Installation',
    jobType: 'Full-Time Commercial Maintenance',
    ageLimit: '20 - 42 Years',
    vacancies: 20,
    location: 'Lahore & Islamabad Commercial Plaza',
    salaryRange: 'PKR 55,000 - 80,000 / month',
    deadline: '2026-10-25',
    description: 'Chiller plant servicing, split AC installation, gas refilling, compressor troubleshooting, and preventive maintenance.',
    requiredSkills: ['AC Repair', 'Gas Charging', 'Compressor Testing'],
    status: 'active',
    campaigns: ['private']
  },
  {
    id: 'job-37',
    title: 'Resident Medical Officer (Doctor)',
    department: 'Shifa Care Specialist Hospital',
    category: 'Private Hospitals & Clinics',
    minQualification: 'Bachelor',
    qualificationRequired: 'MBBS Degree + PMDC Registration',
    medicalQualification: 'PMDC / PMC Valid License',
    experienceRequired: '1 Year Post House Job Experience',
    jobType: 'Full-Time Hospital Duty',
    ageLimit: '23 - 40 Years',
    vacancies: 12,
    location: 'Karachi & Lahore Specialist Centers',
    salaryRange: 'PKR 120,000 - 180,000 / month',
    deadline: '2026-11-10',
    description: 'Monitoring ICU & ward admitted patients, taking emergency consult calls, and managing discharge summaries.',
    requiredSkills: ['Ward Management', 'ICU Care', 'Emergency Resuscitation'],
    status: 'active',
    campaigns: ['private']
  },
  {
    id: 'job-39',
    title: 'Factory Machine Operator & Electrician',
    department: 'Kohinoor Textile Mills',
    category: 'Machine Operators',
    minQualification: 'Matric',
    qualificationRequired: 'Matric / Middle + Technical Diploma',
    experienceRequired: '1 Year Industrial Machine Operation',
    jobType: 'Full-Time Shift Basis',
    ageLimit: '18 - 40 Years',
    vacancies: 40,
    location: 'Faisalabad Industrial Estate',
    salaryRange: 'PKR 38,000 - 55,000 / month',
    deadline: '2026-10-15',
    description: 'Operating weaving & spinning machines, routine lube maintenance, fixing electrical trips, and monitoring output.',
    requiredSkills: ['Machine Operations', 'Safety Protocols', 'Basic Electrical'],
    status: 'active',
    campaigns: ['factory-workers']
  },

  // --- SUTHRA PUNJAB CAMPAIGN DEDICATED JOBS (12 Jobs) ---
  {
    id: 'sp-job-1',
    title: 'Cleaner',
    department: 'Suthra Punjab Sanitation Wing',
    category: 'Cleaner & Sweeper',
    minQualification: 'Primary',
    qualificationRequired: 'Primary Pass',
    jobType: 'Full-Time / Govt Contract',
    ageLimit: '18 - 45 Years',
    vacancies: 120,
    location: 'Punjab Municipal Districts',
    salaryRange: 'PKR 32,000 - 42,000 / month',
    deadline: '2026-10-31',
    description: 'Daily municipal cleanliness, public area sanitation, litter gathering, and waste bin emptying.',
    requiredSkills: ['Street Cleaning', 'Waste Disposal', 'Punctuality'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  {
    id: 'sp-job-2',
    title: 'Sweeper',
    department: 'Suthra Punjab Waste Management Unit',
    category: 'Cleaner & Sweeper',
    minQualification: 'Primary',
    qualificationRequired: 'Primary Pass',
    jobType: 'Full-Time / Shift Work',
    ageLimit: '18 - 45 Years',
    vacancies: 150,
    location: 'All Tehsil Municipalities',
    salaryRange: 'PKR 30,000 - 40,000 / month',
    deadline: '2026-10-31',
    description: 'Sweeping main roads, commercial bazaars, residential streets, and public plazas.',
    requiredSkills: ['Sweeping', 'Public Hygiene', 'Physical Stamina'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  {
    id: 'sp-job-3',
    title: 'Sanitary Worker',
    department: 'Urban Cleanliness & Sanitation Dept',
    category: 'Sanitary Worker',
    minQualification: 'Middle',
    qualificationRequired: 'Middle / Primary',
    jobType: 'Full-Time Field Duty',
    ageLimit: '18 - 40 Years',
    vacancies: 100,
    location: 'Punjab District Headquarters',
    salaryRange: 'PKR 34,000 - 44,000 / month',
    deadline: '2026-11-15',
    description: 'Sanitation operations, chemical spraying, waste collection, and supporting field inspectors.',
    requiredSkills: ['Sanitation Protocols', 'Waste Handling', 'Disinfection'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  {
    id: 'sp-job-4',
    title: 'Garbage Collector',
    department: 'Solid Waste Management Division',
    category: 'Sanitary Worker',
    minQualification: 'Primary',
    qualificationRequired: 'Primary Pass',
    jobType: 'Full-Time Shift Duty',
    ageLimit: '18 - 45 Years',
    vacancies: 80,
    location: 'Urban Municipal Sectors',
    salaryRange: 'PKR 32,000 - 42,000 / month',
    deadline: '2026-10-25',
    description: 'Collecting household waste bins, loading compaction vehicles, and transporting waste to transfer stations.',
    requiredSkills: ['Bin Handling', 'Truck Loading', 'Team Coordination'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  {
    id: 'sp-job-5',
    title: 'Waste Collector',
    department: 'Resource Recovery & Cleanliness Wing',
    category: 'Sanitary Worker',
    minQualification: 'Middle',
    qualificationRequired: 'Middle Pass',
    jobType: 'Full-Time Field Duty',
    ageLimit: '18 - 40 Years',
    vacancies: 70,
    location: 'Commercial Markets & Hubs',
    salaryRange: 'PKR 35,000 - 45,000 / month',
    deadline: '2026-11-05',
    description: 'Commercial waste collection, door-to-door store waste gathering, and sorting recyclable material.',
    requiredSkills: ['Waste Segregation', 'Heavy Lifting', 'Site Cleaning'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  {
    id: 'sp-job-6',
    title: 'Drain Cleaner',
    department: 'Sewerage & Drain Maintenance Wing',
    category: 'Cleaner & Sweeper',
    minQualification: 'Primary',
    qualificationRequired: 'Primary Pass',
    jobType: 'Full-Time / Emergency Operations',
    ageLimit: '18 - 42 Years',
    vacancies: 60,
    location: 'District Drain Operations',
    salaryRange: 'PKR 35,000 - 46,000 / month',
    deadline: '2026-10-30',
    description: 'Clearing clogged street drains, removing sludge, and ensuring smooth rainwater runoff in municipal zones.',
    requiredSkills: ['Drain De-clogging', 'Safety Gear Usage', 'Physical Fitness'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  {
    id: 'sp-job-7',
    title: 'Street Cleaner',
    department: 'Municipal Public Way Care',
    category: 'Cleaner & Sweeper',
    minQualification: 'Primary',
    qualificationRequired: 'Primary Pass',
    jobType: 'Full-Time Outdoor Duty',
    ageLimit: '18 - 45 Years',
    vacancies: 90,
    location: 'Highways & Boulevard Sectors',
    salaryRange: 'PKR 31,000 - 41,000 / month',
    deadline: '2026-10-28',
    description: 'Cleaning boulevard green belts, roadside edges, bus stops, and public walkways.',
    requiredSkills: ['Roadside Cleaning', 'Litter Picking', 'Safety Vest Protocol'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  {
    id: 'sp-job-8',
    title: 'Field Worker',
    department: 'Suthra Punjab Field Operations',
    category: 'Field Staff',
    minQualification: 'Matric',
    qualificationRequired: 'Matriculation (Science/Arts)',
    jobType: 'Full-Time Field Duty',
    ageLimit: '18 - 35 Years',
    vacancies: 85,
    location: 'Tehsil Level Field Squads',
    salaryRange: 'PKR 38,000 - 48,000 / month',
    deadline: '2026-11-10',
    description: 'Assisting field supervisors, logging waste collection progress via mobile app, and public awareness.',
    requiredSkills: ['Mobile App Entry', 'Field Duty', 'Public Communication'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  {
    id: 'sp-job-9',
    title: 'Supervisor',
    department: 'Cleanliness Audit & Supervision',
    category: 'Supervisor & Inspector',
    minQualification: 'Matric',
    qualificationRequired: 'Matric / Intermediate',
    jobType: 'Full-Time Supervisory Contract',
    ageLimit: '20 - 40 Years',
    vacancies: 40,
    location: 'District Tehsil Offices',
    salaryRange: 'PKR 45,000 - 60,000 / month',
    deadline: '2026-11-20',
    description: 'Supervising field workers, tracking daily attendance rosters, and auditing sanitary quality.',
    requiredSkills: ['Team Supervision', 'Attendance Logs', 'Quality Control'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  {
    id: 'sp-job-10',
    title: 'Sanitation Supervisor',
    department: 'Suthra Punjab Quality & Compliance',
    category: 'Supervisor & Inspector',
    minQualification: 'Intermediate',
    qualificationRequired: 'FA / FSc or Equivalent',
    jobType: 'Full-Time Supervisory Post',
    ageLimit: '20 - 38 Years',
    vacancies: 30,
    location: 'Divisional Headquarters',
    salaryRange: 'PKR 48,000 - 65,000 / month',
    deadline: '2026-11-15',
    description: 'Overseeing large-scale urban sanitation drives, compliance checking, and resolving public complaints.',
    requiredSkills: ['Sanitation Standards', 'Complaint Resolution', 'Field Inspection'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  {
    id: 'sp-job-11',
    title: 'Cleaning Supervisor',
    department: 'Commercial & Public Sector Cleaning Unit',
    category: 'Supervisor & Inspector',
    minQualification: 'Intermediate',
    qualificationRequired: 'ICS / FA or Higher',
    jobType: 'Full-Time Supervisory Role',
    ageLimit: '20 - 38 Years',
    vacancies: 25,
    location: 'Major Metro Hubs',
    salaryRange: 'PKR 50,000 - 68,000 / month',
    deadline: '2026-11-18',
    description: 'Managing automated sweeper fleets, digital task dispatching, and shift scheduling.',
    requiredSkills: ['Fleet Dispatching', 'Computer Attendance', 'Shift Management'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  {
    id: 'sp-job-12',
    title: 'Foreman',
    department: 'Equipment & Field Coordination Wing',
    category: 'Foreman & Coordinator',
    minQualification: 'Intermediate',
    qualificationRequired: 'FSc / FA / DAE or Equivalent',
    jobType: 'Full-Time Field Coordinator',
    ageLimit: '22 - 42 Years',
    vacancies: 20,
    location: 'Machinery Depots Punjab',
    salaryRange: 'PKR 52,000 - 72,000 / month',
    deadline: '2026-11-25',
    description: 'Coordinating machinery maintenance, tractor trolley deployments, and leading heavy cleanup operations.',
    requiredSkills: ['Equipment Coordination', 'Site Leadership', 'Safety Management'],
    status: 'active',
    campaigns: ['suthra-punjab']
  },
  ...GOVT_JOBS
];
